PUT http://localhost:3003/api/blogs/5a422b3a1b54a676234d17f9
content-Type: application/json

{
    "title": "Canonical string reduction",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 16,
    "user_id": "61d6b1e7006e6e2c919dfaae"
}